### ISSUE TITLE
Makefile using helm fails

### ISSUE THREAD

**Issue by ashishraman96** [pmorie/osb-starter-pack#100]
The make commands fails because of docker push. 
Error: Unauthorised access to docker.
This happens because the repository is to be created before pushing the image. 
Please add a note in documentation or the Makefile has to be changed to include the name of the user and repository.
Ref: https://success.docker.com/article/getting-unauthorized-authentication-required-when-trying-to-push-image-to-dtr

**Comment by lilic** [comment]
@ashishraman96 Actually you can override the name of the image by overriding the `IMAGE` var like so:  `IMAGE=quay.io/yourrepo/servicebroker make push`.

You can do the same for these: https://github.com/pmorie/osb-starter-pack/blob/79cba221bd275089f7384aaed4bbd601d57468d8/Makefile#L6-L8

**Comment by lilic** [comment]
We also have these documented already, but let me know if the docs are not clear enough, also you are more then welcome to adjust them! :) https://github.com/pmorie/osb-starter-pack#deploy-broker-using-helm

(If there is anything else, we can reopen this issue later.)

**Comment by ashishraman96** [comment]
@LiliC Thank you, I will surely try that out.
