### ISSUE TITLE
First integration test

### ISSUE THREAD

**Issue by pmorie** [pmorie/osb-starter-pack#11]
Let's make an integration test that:

- stubs out the `BusinessLogic` with a fake that just returns a fixed catalog
- uses go-open-service-broker-client to send a catalog request to an instance of this broker
- verifies that the catalog from (1) is `reflect.DeepEqual` to the one received by the client

**Comment by LiliC** [comment]
@pmorie I guess we can close this one and open another issue with "Add additional tests", WDYT?
