### ISSUE TITLE
Extract rest and broker pkgs to a separate library

### ISSUE THREAD

**Issue by LiliC** [pmorie/osb-starter-pack#55]
As discussed before this will make it easier for individual brokers to keep up without needing to rebase agains the osb-starter-pack.

**Comment by pmorie** [comment]
Here's what I have been thinking for the way I'd ultimately like things to fit together:

- `osb-client` is the basic library for the client (currently `go-open-service-broker-client`)
- `osb-broker-lib` vendors `osb-client` for types / some utility methods and constants
- `osb-starter-pack` vendors `osb-client` and `osb-broker-lib` and gives you the 5-minutes-to-broker experience

**Comment by arschles** [comment]
We've talked about this offline, but I believe that we should make the split and move each of these repos under the https://github.com/osbkit org. Say the word and I'll start helping with the move :)

**Comment by pmorie** [comment]
I will move them once i feel they’re in the right state, but yeah that is
my plan
