### ISSUE TITLE
Unable to deploy broker skeleton

### ISSUE THREAD

**Issue by joaquinrdzibm** [pmorie/osb-starter-pack#66]
Hello, I am interested in using your starter-pack to implement a service broker in kubernetes. I followed the instructions and I am getting the following error:
```
ubuntu@cf-broker-master:~/go/src/github.com/pmorie/osb-starter-pack$ make deploy-helm
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
go build -o servicebroker-linux --ldflags="-s" github.com/pmorie/osb-starter-pack/cmd/servicebroker
cp servicebroker-linux image/servicebroker
docker build image/ -t "quay.io/osb-starter-pack/servicebroker:125abe3"
Sending build context to Docker daemon  5.736MB
Step 1/3 : FROM busybox
 ---> 5b0d59026729
Step 2/3 : ADD servicebroker /opt/servicebroker/servicebroker
 ---> Using cache
 ---> a9422d727793
Step 3/3 : CMD /opt/servicebroker/servicebroker --help
 ---> Using cache
 ---> 06ed501e4358
Successfully built 06ed501e4358
Successfully tagged quay.io/osb-starter-pack/servicebroker:125abe3
helm upgrade --install broker-skeleton --namespace broker-skeleton \
charts/servicebroker \
--set image="quay.io/osb-starter-pack/servicebroker:125abe3",imagePullPolicy="IfNotPresent"
Error: UPGRADE FAILED: "broker-skeleton" has no deployed releases
Makefile:31: recipe for target 'deploy-helm' failed
make: *** [deploy-helm] Error 1
```
Seems like the build process works well but the install is not working. Not sure why is using image _quay.io/osb-starter-pack/servicebroker:125abe3_ instead of :latest 

Any help is much appreciated.

Thanks!

**Comment by pmorie** [comment]
Hi-

Thanks for using the repo!

Can I ask, are you deploying against a local cluster or one hosted somewhere off of your machine? If you're using a non-local, you'll need to push the image before it will be usable in the cluster you're deploying to.

You can set the image repository and tag used by setting the `IMAGE` and `TAG` environment variables respectively. You'll also need to use the make target to push the image.

example:

```
$ IMAGE=myimage TAG=latest make push deploy-helm
```

Hope that helps, feel free to ping me on kubernetes slack (nick pmorie) if you get stuck.

**Comment by joaquinrdzibm** [comment]
Thanks, @pmorie, that worked. After changing the IMAGE and TAG, I had an issue that it was not letting me deploy to kubernetes (even if the build and pushing the image was successful).  Had to run a `helm delete --purge broker-skeleton`. Maybe this could be added as a directive either under `clean` or make a new one `clean-helm` ?

**Comment by joaquinrdzibm** [comment]
Closing this issue. Updated documentation helped.
