### ISSUE TITLE
Unable to find originating identity error

### ISSUE THREAD

**Issue by LiliC** [pmorie/osb-starter-pack#74]
I get the following error when trying to use latest release of the https://github.com/pmorie/osb-broker-lib.

```
Warning   ClusterServiceBrokerReturnedFailure   service-catalog-controller-manager   Error provisioning ServiceInstance of ClusterServiceClass (K8S: "50e86479-4c66-4236-88fb-a1e61b4c9448" ExternalName: "redis-habitat") at ClusterServiceBroker "habitat-broker": Status: 400; ErrorMessage: <nil>; Description: unable to find originating identity; ResponseError: <nil>
Warning   DeprovisionCallFailed                 service-catalog-controller-manager   Deprovision call failed; received error response from broker: Status: 500; ErrorMessage: <nil>; Description: unable to find originating identity; ResponseError: <nil>
```

I think I am missing something in my broker? But when the osb-broker-starter-pack was bumped to [`0.0.2`](https://github.com/pmorie/osb-starter-pack/commit/5efdcc57a0f6bdcb9c84c7675275a163d7eb98d0) nothing was changed in the broker code. So I am not sure what would need to be done in the broker side?

cc @pmorie @shawn-hurley

**Comment by LiliC** [comment]
Wasn't sure if I should open this here or the library. Can move this over there as well? Thanks!

**Comment by shawn-hurley** [comment]
Looking into this now.

**Comment by shawn-hurley** [comment]
https://github.com/pmorie/osb-broker-lib/pull/25

I think this should be a quick fix
