### ISSUE TITLE
Provisioning example does not store the service class or plan.

### ISSUE THREAD

**Issue by n3wscott** [pmorie/osb-starter-pack#82]
This will result in provisioning an object of the same id with the same parameters, but different classes and the broker will say this is already created rather than an id collision.

**Comment by pmorie** [comment]
I agree that we should fix this :)

**Comment by n3wscott** [comment]
I have code that does this, I can contribute it back... give me a couple hours

**Comment by pmorie** [comment]
Sgtm

**Comment by LiliC** [comment]
Guess we can close this one, now that the PR was merged.
