### ISSUE TITLE
Return Exists in the Response

### ISSUE THREAD

**Issue by LiliC** [pmorie/osb-starter-pack#83]
Now that https://github.com/pmorie/osb-broker-lib/pull/28 is merged and in a release, we should have an example for this in this project as well. Not sure what is the correct approach, but would be good if we could along the way fix https://github.com/pmorie/osb-starter-pack/issues/82 as well? :) 

cc @shawn-hurley

**Comment by n3wscott** [comment]
#82 fixed in https://github.com/pmorie/osb-starter-pack/pull/84

**Comment by LiliC** [comment]
Guess we can close this, as you added the `Exists` part as well. :) Thanks @n3wscott!
