### ISSUE TITLE
issues with Bearer Token under Kuberenetes

### ISSUE THREAD

**Issue by jboyd01** [pmorie/osb-starter-pack#95]
While rebasing https://github.com/pmorie/osb-starter-pack/pull/92 I  hit several issues:

* even with authenticate set to false, we still include the new authInfo in the broker.yaml - I think the chart needs to conditionally include this
* in my deployment, it appears the secret name is off.  I believe helm created the secret we want by the name "broker-skeleton-broker-skeleton-service-token-p59vc"  but the yaml is specifying {"namespace":"broker-skeleton","name":"broker-skeleton-broker-skeleton"}
* charts/servicebroker/templates/broker-service-account.yaml looks to need "apiGroup: rbac.authorization.k8s.io" under the newly added roleRef in broker-service-account.yaml

**Comment by shawn-hurley** [comment]
Hey Jay,

Wondering if you can give me some more debug steps?
I tested w/ minikube and both authenticate: true and false worked as of last time I tried.

re-attempting now but some more steps would be helpful :)

**Comment by jboyd01** [comment]
No kidding.  I'm working with local-up-cluster.

What happens if you set it to false and delete the cert?  I believe from what I saw in the logs the Broker will return the authInfo structure still and the catalog controller sees it and attempts to load the secret etc.  In my case the secret didn't exist/couldn't be found and it error-ed out even when authenticate was set to false.

I don't think any of this is specific to my PR, but this testing was on my helm-ssl  branch.  I don't use minikube much, usually just local-up-cluster.  I'll make some time to retry with minikube.

I'm at a loss on the secret name differences...  If you can't reproduce I'll run through this again.

**Comment by shawn-hurley** [comment]
This is what I am seeing:

```bash
KIND       NAME
secrets    broker-skeleton-broker-skeleton
```

**Comment by LiliC** [comment]
Maybe it's in a wrong namespace?

**Comment by pmorie** [comment]
I don't think the chart was ever moved away from the 'broker-skeleton'
naming, which we should probably fix.

**Comment by jboyd01** [comment]
This is actually fixed.  Shawn came up with the solution (  use post install hook for creating broker ("helm.sh/hook": post-install)) and its included in https://github.com/pmorie/osb-starter-pack/pull/92 which is ready to be merged.
